name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # auth_repository:
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  flutter_otp_text_field: ^1.1.0+2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  font_awesome_flutter: ^10.7.0
  custom_navigation_bar: ^0.8.2
  simple_animations: ^5.0.2
  supercharged: ^2.1.1

  
dependency_overrides:
  firebase_core_platform_interface: 5.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash.png
  image_dark: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

