// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9hzX5BOMBB5A_-XUHDK5OrKpOWxm_YY',
    appId: '1:7193038287:web:2508db0d6b16b48d79d6ba',
    messagingSenderId: '7193038287',
    projectId: 'flutter-app-42f81',
    authDomain: 'flutter-app-42f81.firebaseapp.com',
    storageBucket: 'flutter-app-42f81.appspot.com',
    measurementId: 'G-PGDZN28F7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr90LNlhSGp4XaN2TuYo4EADZWgcb4QfM',
    appId: '1:7193038287:android:5952f76da86ad6f779d6ba',
    messagingSenderId: '7193038287',
    projectId: 'flutter-app-42f81',
    storageBucket: 'flutter-app-42f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zm9Bi3qSArnKgYO6JLpnIj0O810PxpY',
    appId: '1:983788459182:ios:b9f3d9caa7c9d040ec893f',
    messagingSenderId: '983788459182',
    projectId: 'flutter-app-9593b',
    storageBucket: 'flutter-app-9593b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2zm9Bi3qSArnKgYO6JLpnIj0O810PxpY',
    appId: '1:983788459182:ios:b9f3d9caa7c9d040ec893f',
    messagingSenderId: '983788459182',
    projectId: 'flutter-app-9593b',
    storageBucket: 'flutter-app-9593b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ONRdloJ01YG-Ya5vuFvkCIrRDFJz-KQ',
    appId: '1:983788459182:web:81fffd91143f98a4ec893f',
    messagingSenderId: '983788459182',
    projectId: 'flutter-app-9593b',
    authDomain: 'flutter-app-9593b.firebaseapp.com',
    storageBucket: 'flutter-app-9593b.appspot.com',
    measurementId: 'G-V3VGE6K181',
  );
}